#!/usr/bin/env bash
# configure domain zone so `www` points to `1b-01`, `web-01`, `web-02`
if [ "$#" -eq 1 ]
then
    dig www."$1" | grep -e ^www | awk '{print "The subdomain www is a", $4, "record and points to", $5}'
    dig lb-01."$1" | grep -e ^lb-01 | awk '{print "The subdomain lb-01 is a", $4, "record and points to", $5}'
    dig web-01."$1" | grep -e ^web-01 | awk '{print "The subdomain web-01 is a", $4, "record and points to", $5}'
    dig web-02."$1" | grep -e ^web-02 | awk '{print "The subdomain web-02 is a", $4, "record and points to", $5}'
else
    dig "$2.$1" | awk -v type="$2" -F '\t| ' '$1~"^"type { print "The subdomain "type" is a "$4" record and points to "$5 }'
fi
