#!/usr/bin/env bash
# configure nginx HTTP response custom headers on web-01 and web-02
sudo apt-get update
sudo apt-get -y install nginx
c_head="\n\t\# Add custom header\n\tadd_header X-Served-By $HOSTNAME;\n"
sudo sed -i "26i\ $c_head" /etc/nginx/nginx.conf
sudo service nginx restart
