#!/usr/bin/env bash
# configure nginx HTTP response custom headers on web-01 and web-02
c_head="\n\tlocation {\n\t\t\# Add custom header\n\t\tadd_header X-Served-By $HOSTNAME;\n\t}"
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "26i\ $c_head" /etc/nginx/sites-available/default
sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart