#!/usr/bin/env bash
# install and configure HXProxy
sudo apt-get update
sudo apt-get -y install haproxy
replace="ENABLED=0"
with="ENABLED=1"
sudo sed -i "s/$replace/$with" /etc/default/haproxy
sudo sed -i "$ a\listen appname 0.0.0.0:80\n\tmode http" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tstats enable\n\tbalance roundrobin" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \toption httpclose\n\toption forwardfor" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tserver 259-web-01 54.152.200.18:80 check" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tserver 259-web-02 54.224.57.104:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart