#!/usr/bin/env bash
# script configures server to listen on port 80
sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
curl 0:80