#!/usr/bin/env bash
# display "To infinity and beyond," various signals when kills, terms attempted

echo $$ > /var/run/holbertonscript.pid
trap "echo I hate the kill command; exit" SIGTERM
trap "{ rm -f /var/run/holbertonscript.pid; exit }" SIGQUIT
trap "echo Y U no love me?!; exit" SIGINT

loop=0
while [ $loop ]
do
	echo "To infinity and beyond";
	sleep 2;
done
