#!/usr/bin/env bash
# terminates 4-to_infinity_and_beyond process

# ps aux | grep ./4-to_infinity_and_beyond | awk '{print $2}' | xargs kill
kill "$(ps aux | egrep '[.]/4-to_infinity_and_beyond' | awk '{print $2}')"
