#!/usr/bin/env bash
# beheads the 7-highlander process

# ps aux | egrep '[.]/4-to_infinity_and_beyond' | awk '{print $2}' |
kill -SIGKILL "$(ps aux | egrep '[.]/7-highlander' | awk '{print $2}')"
# pkill -f ./7-highlander
