#!/usr/bin/env bash
# display "Holberton School" ten times, w/ "Hi" after the nineth iteration

i=0

while [ $i -lt 10 ]
do
	echo Holberton School
	((i++))
	if [ $i -eq 9 ]
	then
	    echo Hi
	fi
done
