#!/usr/bin/env bash
# displays "Holberton School" eight times, "bad luck" at ln4, "good luck" at ln8

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
	    echo bad luck
	    ((i++))
	elif [  $i -eq 8 ]
	then
	    echo good luck
	    ((i++))
	else
	echo Holberton School
	((i++))
	fi
done
