#!/usr/bin/env bash
# displays numbers from 1 to 20, w/ "bad luck" at ln4, ln9, ln17

num=1

while [ $num -le 20 ]
do
    echo $num
    case $num in
	4) echo bad luck from China;;
	9) echo bad luck from Japan;;
	17) echo bad luck from Italy;;
    esac
    ((num++))
done
