#!/usr/bin/env bash
# displays time for 12 hours, 59 minutes

hr=0

while [ $hr -le 12 ]
do
    min=1

    echo Hour: $hr
    while [ $min -lt 60 ]
    do
	echo $min
	((min++))
    done
    ((hr++))
done
