#!/usr/bin/env bash
# configure nginx to redirect to another page
sudo apt-get -y update
sudo apt-get -y install nginx

new_string="\tlocation /redirect_me {\n\t\treturn 301;\n\t\t}\n"

sudo sed -i "38i\ $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
