#!/usr/bin/env bash
# configures container to requirements
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 744 /etc/nginx/nginx.conf
sudo pkill -f apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown -R 744 /etc/nginx/nginx.conf
sudo -u nginx nginx