#!/usr/bin/env bash
# configures container to requirements
sudo pkill -f apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo chmod -R 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
