#!/usr/bin/env bash
# configures container to requirements
sudo service apache2 stop
sudo pkill apache2
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo chown nginx:nginx /etc/nginx/nginx.conf
chown -R 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
